const VIDEO_KEY='creatix-movies:manual-videos:v1';
const SOURCE_KEY='creatix-movies:catalog-sources:v1';
const PASS_KEY='creatix-movies:settings-pass:v1';
const $=s=>document.querySelector(s), lockCard=$('#lock-card'),admin=$('#admin'),lockForm=$('#lock-form'),passInput=$('#password'),help=$('#lock-help'),lockTitle=$('#lock-title'),sourceForm=$('#source-form'),typeSelect=$('#content-type'),seriesFields=$('#series-fields'),list=$('#manual-list'),message=$('#message'),catalogForm=$('#catalog-source-form'),catalogMessage=$('#catalog-source-message'),catalogList=$('#catalog-source-list');
const enc=new TextEncoder();
async function hash(v){const b=await crypto.subtle.digest('SHA-256',enc.encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function read(key){try{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function save(key,v){localStorage.setItem(key,JSON.stringify(v))}
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function updateLockCopy(){const exists=!!localStorage.getItem(PASS_KEY);lockTitle.textContent=exists?'Accès protégé':'Créer le code d’accès';help.textContent=exists?'Entre ton code pour gérer tes sources.':'Choisis un code d’au moins 4 caractères.';lockForm.querySelector('button').textContent=exists?'Déverrouiller':'Créer le code'}
function unlock(){lockCard.hidden=true;admin.hidden=false;renderAll()}
function lock(){admin.hidden=true;lockCard.hidden=false;passInput.value='';updateLockCopy()}
lockForm.addEventListener('submit',async e=>{e.preventDefault();const v=passInput.value.trim();if(v.length<4){help.textContent='Utilise au moins 4 caractères.';return}const d=await hash(v),cur=localStorage.getItem(PASS_KEY);if(!cur){localStorage.setItem(PASS_KEY,d);unlock()}else if(d===cur)unlock();else help.textContent='Code incorrect.'});
typeSelect.addEventListener('change',()=>seriesFields.hidden=typeSelect.value!=='episode');
function parsePlayback(url){const u=new URL(url);if(u.protocol!=='https:')throw Error('Utilise une URL HTTPS.');const h=u.hostname.replace(/^www\./,'');if(h.includes('youtube.com')||h==='youtu.be'){const id=h==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v');if(!id)throw Error('Lien YouTube invalide');return {source:'youtube',videoId:id,embeddable:true,label:'YouTube · ajout manuel'}}if(h.includes('dailymotion.com')||h==='dai.ly'){const id=h==='dai.ly'?u.pathname.slice(1):u.pathname.split('/').filter(Boolean).pop();if(!id)throw Error('Lien Dailymotion invalide');return {source:'dailymotion',videoId:id,embeddable:true,label:'Dailymotion · ajout manuel'}}if(h.includes('vimeo.com')){const id=u.pathname.split('/').filter(Boolean).pop();if(!/^\d+$/.test(id||''))throw Error('Lien Vimeo invalide');return {source:'vimeo',videoId:id,embeddable:true,label:'Vimeo · ajout manuel'}}if(h==='archive.org'){const p=u.pathname.split('/').filter(Boolean),i=p.indexOf('details'),id=i>=0?p[i+1]:null;if(!id)throw Error('Lien Archive invalide');return {source:'archive',videoId:id,embeddable:true,label:'Internet Archive · ajout manuel'}}if(/\.m3u8(?:$|\?)/i.test(url))return {source:'hls',playbackUrl:url,embeddable:true,label:'HLS · ajout manuel'};if(/\.webm(?:$|\?)/i.test(url))return {source:'webm',playbackUrl:url,embeddable:true,label:'WebM · ajout manuel'};if(/\.mp4(?:$|\?)/i.test(url))return {source:'mp4',playbackUrl:url,embeddable:true,label:'MP4 · ajout manuel'};throw Error('Source vidéo non reconnue.')}
sourceForm.addEventListener('submit',e=>{e.preventDefault();message.textContent='';try{const title=$('#title').value.trim(),url=$('#url').value.trim(),genre=$('#genre').value.trim(),duration=Math.max(60,Number($('#duration').value||0)*60),contentType=typeSelect.value,playback=parsePlayback(url),now=new Date().toISOString();const item={id:`manual:${Date.now()}`,source:'manual',title,channel:'Ajout manuel',description:'Source ajoutée manuellement.',thumbnail:'',status:'replay',durationSeconds:duration,contentType,language:'fr',topics:genre?[genre]:[],score:100,embeddable:true,sourceUrl:url,lastCheckedAt:now,verification:'manual',playbackSources:[playback]};if(contentType==='episode'){item.seriesTitle=$('#series-title').value.trim()||title;item.seasonNumber=Math.max(1,Number($('#season').value||1));item.episodeNumber=Math.max(1,Number($('#episode').value||1));item.topics=['Série',...item.topics]}const rows=read(VIDEO_KEY);rows.push(item);save(VIDEO_KEY,rows);sourceForm.reset();$('#duration').value=45;typeSelect.value='film';seriesFields.hidden=true;message.textContent='Ajout enregistré.';renderVideos()}catch(err){message.textContent=err.message}});
function extractRows(payload){if(Array.isArray(payload))return payload;if(Array.isArray(payload?.videos))return payload.videos;if(Array.isArray(payload?.items))return payload.items;if(Array.isArray(payload?.catalog))return payload.catalog;return null}
catalogForm.addEventListener('submit',async e=>{e.preventDefault();catalogMessage.textContent='Test de la source…';try{const name=$('#catalog-source-name').value.trim(),url=$('#catalog-source-url').value.trim(),type=$('#catalog-source-type').value,u=new URL(url);if(u.protocol!=='https:')throw Error('Le catalogue doit utiliser HTTPS.');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);let response;try{response=await fetch(url,{cache:'no-store',signal:controller.signal})}finally{clearTimeout(timer)}if(!response.ok)throw Error(`La source répond HTTP ${response.status}.`);const payload=await response.json(),rows=extractRows(payload);if(!rows)throw Error('JSON reconnu, mais aucune liste videos/items/catalog trouvée.');if(!rows.length)throw Error('Le catalogue est vide.');const sources=read(SOURCE_KEY).filter(s=>s.url!==url);sources.push({id:`catalog:${Date.now()}`,name,url,type,enabled:true,lastTestedAt:new Date().toISOString(),detectedItems:rows.length});save(SOURCE_KEY,sources);catalogForm.reset();catalogMessage.textContent=`Source ajoutée : ${rows.length} éléments détectés.`;renderSources()}catch(err){catalogMessage.textContent=err.name==='AbortError'?'La source met trop de temps à répondre.':`Impossible d’ajouter : ${err.message}. Vérifie aussi que le serveur autorise CORS.`}});
function renderSources(){const rows=read(SOURCE_KEY);catalogList.innerHTML=rows.length?rows.map(s=>`<div class="manual-row"><div><strong>${esc(s.name)}</strong><small>${esc(s.type==='mixed'?'Films + séries':s.type==='film'?'Films':'Séries')} · ${Number(s.detectedItems||0)} éléments<br>${esc(s.url)}</small></div><button type="button" data-delete-source="${esc(s.id)}">Supprimer</button></div>`).join(''):'<p class="empty">Aucune source de catalogue ajoutée.</p>'}
function renderVideos(){const rows=read(VIDEO_KEY);list.innerHTML=rows.length?rows.map(v=>`<div class="manual-row"><div><strong>${esc(v.title)}</strong><small>${v.contentType==='episode'?'Série':'Film'}</small></div><button type="button" data-delete="${esc(v.id)}">Supprimer</button></div>`).join(''):'<p class="empty">Aucun ajout manuel.</p>'}
function renderAll(){renderSources();renderVideos()}
catalogList.addEventListener('click',e=>{const b=e.target.closest('[data-delete-source]');if(!b)return;save(SOURCE_KEY,read(SOURCE_KEY).filter(s=>s.id!==b.dataset.deleteSource));renderSources()});list.addEventListener('click',e=>{const b=e.target.closest('[data-delete]');if(!b)return;save(VIDEO_KEY,read(VIDEO_KEY).filter(v=>v.id!==b.dataset.delete));renderVideos()});$('#lock-now').addEventListener('click',lock);updateLockCopy();